export const MODAL_TYPES = {
	disabled: "DISABLED",
	notConnected: "NOT_CONNECTED",
	disconnected: "DISCONNECTED",
	selectChain: "SELECT_CHAIN",
	chainNotAdded: "CHAIN_NOT_ADDED",
	pleaseConnect: "PLEASE_CONNECT",
	incompleteForm: "INCOMPLETE_FORM",
	unavailableName: "NAME_UNAVAILABLE",
	unavailableCoordinates: "COORDINATES_UNAVAILABLE",
	contractCallFailed: "CONTRACT_CALL_FAILED",
	txRejected: "TRANSACTION_REJECTED",
	tokenNotOwned: "TOKEN_NOT_OWNED",
	tokenAlreadyOwned: "TOKEN_ALREADY_OWNED",
	tokenNotForSale: "TOKEN_NOT_FOR_SALE",
	tokenAlreadyForSale: "TOKEN_ALREADY_FOR_SALE",
	tokenIdenticalPrice: "TOKEN_IDENTICAL_PRICE",
	tokenDifferentPrice: "TOKEN_DIFFERENT_PRICE",
};
